# Generated by Django 4.1 on 2022-08-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteinmodel',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='proteinmodel',
            name='accession',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='proteinmodel',
            name='cellular_processes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='proteinmodel',
            name='protein_functions',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='proteinmodel',
            name='reactome_pathways',
            field=models.TextField(default=''),
        ),
    ]
