# Generated by Django 4.1 on 2022-08-09 08:41

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_proteinmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='proteinabundancemodel',
            managers=[
                ('proteins', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='proteinmodel',
            managers=[
                ('proteins', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='proteinabundancemodel',
            name='protein_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protein_data', to='api.proteinmodel'),
        ),
    ]
