# Generated by Django 4.1 on 2022-08-09 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_proteinabundancemodel_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proteinabundancemodel',
            options={'ordering': ['upload_date', 'hour']},
        ),
        migrations.AlterModelOptions(
            name='proteinmodel',
            options={'ordering': ['upload_date', 'protein_id']},
        ),
        migrations.AddField(
            model_name='proteinabundancemodel',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proteinmodel',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
